USE [LOE01]
GO
/****** Object:  Trigger [dbo].[AUFTRAGSKOPF_CODE3]    Script Date: 09.12.2020 08:32:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER [dbo].[AUFTRAGSKOPF_CODE3]
   ON  [dbo].[AUFTRAGSKOPF]
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
	DECLARE @CodeAlt varchar(40)
	DECLARE @CodeNeu varchar(40)
	DECLARE @Beleg decimal(15, 0)

	SELECT @CodeAlt = INSERTED.CODE3
		FROM INSERTED
	SELECT @CodeNeu = INSERTED.CODE1
		FROM INSERTED
	Select @Beleg = INSERTED.BELEGNR
		FROM INSERTED

	IF @CodeNeu LIKE '%@%' OR @CodeAlt LIKE ''
			UPDATE [dbo].[AUFTRAGSKOPF] SET CODE3 = @CodeNeu WHERE BELEGNR = @Beleg
END
