USE [LOE01]
GO
/****** Object:  Trigger [dbo].[AUFTRAGSKOPF_VERSANDART]    Script Date: 30.07.2019 14:10:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER [dbo].[AUFTRAGSKOPF_VERSANDART]
   ON  [dbo].[AUFTRAGSKOPF]
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;

	DECLARE @VersandartAlt smallint
	DECLARE @Beleg decimal(15, 0)
	DECLARE @Auftragsart varchar(4)

	SELECT @VersandartAlt = INSERTED.VANUMMER
		FROM INSERTED
	SELECT @Beleg = INSERTED.BELEGNR
		FROM INSERTED
	SELECT @Auftragsart = INSERTED.BELEGART
		FROM INSERTED

	IF @VersandartAlt = 3 AND @Auftragsart = 16
		UPDATE [dbo].[AUFTRAGSKOPF] SET VANUMMER = 18 WHERE BELEGNR = @Beleg
END
