-- Set KEK
Use [LOE01]
go

with cte as (
	SELECT ARTIKELNR, SUM(MENGE) AS SUMMENGE FROM dbo.RESERVIERUNG GROUP BY ARTIKELNR
)

UPDATE dbo.ARTIKEL 
SET KALKBASIS = 2, 
VK3 = CASE WHEN KALK3 is not null THEN KEK*KALK3/100 ELSE KEK*1.05 END,
VK2 = KEK,
KALK2 = 100,
SACHBEARBEITERNR = 'KEKLEKJOB',
AENDERUNGSDATUM = GETDATE()

FROM dbo.ARTIKEL 

INNER JOIN dbo.LAGER on dbo.LAGER.ARTIKELNR = dbo.ARTIKEL.ARTIKELNR 
LEFT JOIN cte on cte.ARTIKELNR = dbo.ARTIKEL.ARTIKELNR

WHERE BUCHBESTAND-ISNULL(SUMMENGE, 0) <= 0 
AND KALKBASIS = 0 
AND LAGERNR = 1

go







-- Set LEK
Use [LOE01]
go

with cte as (
	SELECT ARTIKELNR, SUM(MENGE) AS SUMMENGE FROM dbo.RESERVIERUNG GROUP BY ARTIKELNR
)

UPDATE dbo.ARTIKEL 
SET KALKBASIS = 0, 
VK3 =  CASE WHEN KALK3 is not null THEN LEK*KALK3/100 ELSE LEK*1.05 END,
VK2 = LEK,
KALK2 = 100,
SACHBEARBEITERNR = 'KEKLEKJOB',
AENDERUNGSDATUM = GETDATE()

FROM dbo.ARTIKEL
INNER JOIN dbo.LAGER on dbo.LAGER.ARTIKELNR = dbo.ARTIKEL.ARTIKELNR 
LEFT JOIN cte on cte.ARTIKELNR = dbo.ARTIKEL.ARTIKELNR

WHERE BUCHBESTAND-ISNULL(SUMMENGE, 0) > 0 
AND KALKBASIS = 2 
AND LAGERNR = 1
AND LEK > 0

go
