WITH cte AS (
    SELECT TOP 9999000000 dbo.PREISGRUPPEN.ARTIKELNR, KEK, PREIS, dbo.PREISGRUPPEN.ROWID 
    FROM dbo.PREISGRUPPEN, dbo.ARTIKEL 
    WHERE dbo.PREISGRUPPEN.GRUPPE = 5 AND dbo.PREISGRUPPEN.ARTIKELNR = dbo.ARTIKEL.ARTIKELNR AND dbo.ARTIKEL.GELOESCHT is null
	ORDER BY dbo.PREISGRUPPEN.ARTIKELNR, dbo.PREISGRUPPEN.ROWID desc
)

SELECT cte.ARTIKELNR, CAST((cte.KEK*1.15) as  decimal(16,2)) as VK5neu, cte.PREIS as VK5alt, CAST(cte.KEK as decimal(16,2)) as KEK
FROM cte
INNER JOIN (
    SELECT ARTIKELNR, MAX(ROWID) AS ROWID
    FROM cte
    GROUP BY ARTIKELNR
) AS A
ON cte.ARTIKELNR = A.ARTIKELNR AND cte.ROWID = A.ROWID
WHERE KEK > PREIS
