use LOE01

UPDATE [dbo].[LAGER] SET [dbo].[LAGER].LAGERPLATZ = SUBSTRING([P116LI_TempMax], 0, 8) FROM [dbo].[LAGER] INNER JOIN [dbo].[ARTIKEL] ON [dbo].[LAGER].[ARTIKELNR] = [dbo].[ARTIKEL].[ARTIKELNR];
